<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="UMESH" failures="2" tests="8" name="Test" time="72.09" errors="0" timestamp="2024-01-05T12:17:41 IST">
  <testcase classname="pages.test.PageTest3" name="test1" time="0.357"/>
  <testcase classname="pages.test.PageTest3" name="test2" time="0.0"/>
  <testcase classname="pages.test.PageTest3" name="test3" time="0.017">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at pages.test.PageTest3.test3(PageTest3.java:26)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1623)
... Removed 10 stack frames]]>
    </failure>
  </testcase> <!-- test3 -->
  <testcase classname="pages.test.PageTest3" name="test4" time="0.002"/>
  <testcase classname="pages.test.PageTest3" name="test5" time="0.006"/>
  <testcase classname="pages.test.PageTest2" name="test1" time="0.011"/>
  <testcase classname="pages.test.PageTest2" name="test3" time="1.012">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at pages.test.PageTest2.test3(PageTest2.java:29)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1623)
... Removed 10 stack frames]]>
    </failure>
  </testcase> <!-- test3 -->
  <testcase classname="pages.test.PageTest2" name="test4" time="1.04"/>
</testsuite> <!-- Test -->
