<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="UMESH" failures="1" tests="5" name="pages.test.PageTest3" time="113.180" errors="0" timestamp="2024-01-05T22:24:53 IST" skipped="0">
  <testcase classname="pages.test.PageTest3" name="test1_PageTest3" time="4.642"/>
  <system-out/>
  <testcase classname="pages.test.PageTest3" name="test5_PageTest3" time="4.426"/>
  <system-out/>
  <testcase classname="pages.test.PageTest3" name="test2_PageTest3" time="78.893"/>
  <system-out/>
  <testcase classname="pages.test.PageTest3" name="test4_PageTest3" time="4.386"/>
  <system-out/>
  <testcase classname="pages.test.PageTest3" name="test3_PageTest3" time="20.833">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at pages.test.PageTest3.test3_PageTest3(PageTest3.java:17)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1623)
]]>
    </failure>
  </testcase> <!-- test3_PageTest3 -->
  <system-out/>
</testsuite> <!-- pages.test.PageTest3 -->
